"""Add wallet

Revision ID: 928de8f9faf8
Revises: 1c011c4842ff
Create Date: 2026-06-26 17:33:04.211535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928de8f9faf8'
down_revision: Union[str, Sequence[str], None] = '1c011c4842ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_transactions_wallet_id_wallets'), 'wallets', ['wallet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_wallet_id_wallets'), type_='foreignkey')

    # ### end Alembic commands ###
